# Generated by Django 5.1.4 on 2026-09-10 03:26

import django.db.models.deletion
import fees.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('branches', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='code · কোড')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=80, verbose_name='নাম')),
                ('note', models.TextField(blank=True, verbose_name='note · নোট')),
                ('note_bn', models.TextField(blank=True, verbose_name='নোট')),
                ('recurrence', models.CharField(choices=[('one_time', 'One time · এককালীন'), ('monthly', 'Monthly · মাসিক'), ('session', 'Per session · শিক্ষাবর্ষভিত্তিক'), ('exam', 'Per exam · পরীক্ষাভিত্তিক'), ('custom', 'Custom · প্রযোজ্য ক্ষেত্রে')], default='custom', max_length=20, verbose_name='recurrence · পুনরাবৃত্তি')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='default amount · নির্ধারিত পরিমাণ')),
                ('is_refundable', models.BooleanField(default=False, verbose_name='refundable · ফেরতযোগ্য')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='mandatory · আবশ্যিক')),
                ('applies_to', models.JSONField(blank=True, default=fees.models.default_applies_to, verbose_name='applies to · প্রযোজ্য')),
                ('is_system', models.BooleanField(default=False, verbose_name='seeded · পূর্বনির্ধারিত')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='order · ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fee category · ফি খাত',
                'verbose_name_plural': 'fee categories · ফি খাতসমূহ',
                'ordering': ['branch', 'display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(blank=True, default='', help_text='YYYY-MM for a monthly charge; blank otherwise.', max_length=7, verbose_name='period · মাস')),
                ('invoice_no', models.CharField(max_length=30, verbose_name='invoice no · বিল নম্বর')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount · পরিমাণ')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount · ছাড়')),
                ('fine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='fine · জরিমানা')),
                ('payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='payable · প্রদেয়')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='paid · পরিশোধিত')),
                ('due_date', models.DateField(verbose_name='due date · শেষ তারিখ')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid · বকেয়া'), ('partial', 'Partly paid · আংশিক পরিশোধিত'), ('paid', 'Paid · পরিশোধিত'), ('overdue', 'Overdue · মেয়াদোত্তীর্ণ'), ('waived', 'Waived · মওকুফ')], default='unpaid', help_text='Derived. Never written from a request body.', max_length=20, verbose_name='status · অবস্থা')),
                ('waived_at', models.DateTimeField(blank=True, null=True, verbose_name='waived at · মওকুফের সময়')),
                ('waive_reason', models.TextField(blank=True, verbose_name='waive reason · মওকুফের কারণ')),
                ('generated_by', models.CharField(choices=[('system', 'System · স্বয়ংক্রিয়'), ('manual', 'Manual · হাতে তৈরি')], default='manual', max_length=10, verbose_name='raised by · উৎস')),
                ('note', models.TextField(blank=True, verbose_name='note · মন্তব্য')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='academics.enrolment', verbose_name='enrolment · ভর্তি')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='branches.session', verbose_name='session · শিক্ষাবর্ষ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='students.student', verbose_name='student · শিক্ষার্থী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='waived by · মওকুফকারী')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='fees.feecategory', verbose_name='category · খাত')),
            ],
            options={
                'verbose_name': 'fee · ফি',
                'verbose_name_plural': 'fees · ফিসমূহ',
                'ordering': ['branch', '-due_date', 'student', 'category'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=30, verbose_name='receipt no · রসিদ নম্বর')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount · পরিমাণ')),
                ('method', models.CharField(choices=[('cash', 'Cash · নগদ টাকা'), ('bkash', 'bKash · বিকাশ'), ('nagad', 'Nagad · নগদ'), ('rocket', 'Rocket · রকেট'), ('bank', 'Bank · ব্যাংক'), ('cheque', 'Cheque · চেক'), ('card', 'Card · কার্ড'), ('online', 'Online · অনলাইন')], default='cash', max_length=20, verbose_name='method · মাধ্যম')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=80, verbose_name='transaction id · লেনদেন আইডি')),
                ('paid_at', models.DateTimeField(verbose_name='paid at · আদায়ের সময়')),
                ('note', models.TextField(blank=True, verbose_name='note · মন্তব্য')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed · বাতিল')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at · বাতিলের সময়')),
                ('reverse_reason', models.TextField(blank=True, verbose_name='reversal reason · বাতিলের কারণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='collected by · আদায়কারী')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.fee', verbose_name='fee · ফি')),
            ],
            options={
                'verbose_name': 'payment · আদায়',
                'verbose_name_plural': 'payments · আদায়সমূহ',
                'ordering': ['branch', '-paid_at', '-id'],
                'abstract': False,
            },
        ),
    ]
