# Generated by Django 5.1.4 on 2026-09-10 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.income', verbose_name='income row · আয় এন্ট্রি'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by · বাতিলকারী'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='student · শিক্ষার্থী'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feecategory',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='feecategory_unique_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['branch', 'status', 'due_date'], name='fee_branch_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['student', 'session'], name='fee_student_session_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['branch', 'period'], name='fee_branch_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('branch', 'student', 'category', 'period', 'session'), name='fee_unique_per_student_category_period'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('branch', 'invoice_no'), name='fee_unique_invoice_no'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('discount__gte', 0), ('fine__gte', 0), ('paid_amount__gte', 0)), name='fee_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('amount'))), name='fee_discount_within_amount'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'paid_at'], name='payment_branch_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'paid_at'], name='payment_student_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('branch', 'receipt_no'), name='payment_unique_receipt_no'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('branch', 'method', 'transaction_id'), name='payment_unique_txn_per_method'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
