# Generated by Django 5.1.4 on 2026-09-19 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('branches', '0002_register_edit_days'),
        ('fees', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fee',
            name='fee_unique_per_student_category_period',
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch', 'student', 'category', 'period', 'session'), name='fee_unique_per_student_category_period'),
        ),
    ]
