# Generated by Django 5.1.4 on 2026-09-10 02:06

import branches.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=150, verbose_name='নাম')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم')),
                ('institution_type', models.CharField(choices=[('madrasah', 'Madrasah · মাদ্রাসা'), ('school', 'School · স্কুল'), ('college', 'College · কলেজ'), ('combined', 'Combined · সমন্বিত')], default='madrasah', max_length=20, verbose_name='institution type · প্রতিষ্ঠানের ধরন')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code · কোড')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='established year · প্রতিষ্ঠাকাল')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('address_bn', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='district · জেলা')),
                ('thana', models.CharField(blank=True, max_length=80, verbose_name='thana · থানা')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone · ফোন')),
                ('alt_phone', models.CharField(blank=True, max_length=20, verbose_name='alternate phone · বিকল্প ফোন')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email · ইমেইল')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branches/logos/', verbose_name='logo · লোগো')),
                ('fine_rule', models.JSONField(blank=True, default=branches.models.default_fine_rule, verbose_name='fine rule · জরিমানার নিয়ম')),
                ('attendance_window_minutes', models.PositiveIntegerField(default=120, verbose_name='attendance window (minutes) · হাজিরার সময়সীমা')),
                ('restrict_teachers_to_assigned_classes', models.BooleanField(default=True, verbose_name='restrict teachers to assigned classes · শিক্ষককে নির্ধারিত ক্লাসে সীমাবদ্ধ রাখুন')),
                ('activity_retention_days', models.PositiveIntegerField(default=180, verbose_name='activity retention (days) · কার্যক্রম সংরক্ষণ (দিন)')),
                ('weekly_off_days', models.JSONField(blank=True, default=branches.models.default_weekly_off_days, verbose_name='weekly off days · সাপ্তাহিক ছুটি')),
                ('sms_sender_id', models.CharField(blank=True, max_length=20, verbose_name='SMS sender id · এসএমএস প্রেরক')),
                ('default_language', models.CharField(choices=[('bn', 'বাংলা · Bangla'), ('en', 'English · ইংরেজি')], default='bn', max_length=2, verbose_name='default language · ডিফল্ট ভাষা')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='head · প্রধান')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institution · প্রতিষ্ঠান',
                'verbose_name_plural': 'institutions · প্রতিষ্ঠানসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, verbose_name='name · নাম')),
                ('starts_on', models.DateField(verbose_name='starts on · শুরু')),
                ('ends_on', models.DateField(verbose_name='ends on · শেষ')),
                ('is_current', models.BooleanField(default=False, verbose_name='current · চলতি')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session · শিক্ষাবর্ষ',
                'verbose_name_plural': 'sessions · শিক্ষাবর্ষসমূহ',
                'ordering': ['branch', '-starts_on', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_branches', to='branches.session', verbose_name='current session · চলতি শিক্ষাবর্ষ'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='code · কোড')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=60, verbose_name='নাম')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order · ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stream · শাখা',
                'verbose_name_plural': 'streams · শাখাসমূহ',
                'ordering': ['branch', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='streams',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='branches.stream', verbose_name='streams · শাখাসমূহ'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active', 'name'], name='branch_active_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='stream_unique_code_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='session_unique_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='session_ends_after_start'),
        ),
    ]
