# Generated by Django 5.1.4 on 2026-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='register_edit_days',
            field=models.PositiveIntegerField(default=3, help_text='How many days back a teacher may still mark the daily register. 0 = no limit.', verbose_name='register edit window (days) · রেজিস্টার সংশোধনের সময় (দিন)'),
        ),
    ]
