# Generated by Django 5.1.4 on 2026-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_register_edit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sms_enabled',
            field=models.BooleanField(default=True, verbose_name='send SMS · এসএমএস পাঠানো হবে'),
        ),
    ]
