# Generated by Django 5.1.4 on 2026-09-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sms_on_admission',
            field=models.BooleanField(default=False, verbose_name='SMS on admission · ভর্তিতে এসএমএস'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sms_on_payment',
            field=models.BooleanField(default=False, verbose_name='SMS on payment · ফি জমায় এসএমএস'),
        ),
    ]
