# Generated by Django 5.1.4 on 2026-09-10 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='code · কোড')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=80, verbose_name='নাম')),
                ('note', models.TextField(blank=True, verbose_name='note · নোট')),
                ('note_bn', models.TextField(blank=True, verbose_name='নোট')),
                ('is_system', models.BooleanField(default=False, verbose_name='seeded · পূর্বনির্ধারিত')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='order · ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expense category · ব্যয়ের খাত',
                'verbose_name_plural': 'expense categories · ব্যয়ের খাতসমূহ',
                'ordering': ['branch', 'display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_no', models.CharField(max_length=30, verbose_name='voucher no · ভাউচার নম্বর')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount · পরিমাণ')),
                ('date', models.DateField(verbose_name='date · তারিখ')),
                ('method', models.CharField(choices=[('cash', 'Cash · নগদ টাকা'), ('bkash', 'bKash · বিকাশ'), ('nagad', 'Nagad · নগদ'), ('rocket', 'Rocket · রকেট'), ('bank', 'Bank · ব্যাংক'), ('cheque', 'Cheque · চেক'), ('card', 'Card · কার্ড'), ('online', 'Online · অনলাইন')], default='cash', max_length=20, verbose_name='method · মাধ্যম')),
                ('reference', models.CharField(blank=True, default='', help_text='Transaction id, cheque number, bill number.', max_length=120, verbose_name='reference · সূত্র')),
                ('description', models.TextField(blank=True, verbose_name='description · বিবরণ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/vouchers/%Y/%m/', verbose_name='attachment · সংযুক্তি')),
                ('source', models.CharField(choices=[('manual', 'Entered manually · হাতে লেখা'), ('fee_payment', 'Fee collection · ফি আদায়'), ('payroll', 'Payroll · বেতন')], default='manual', max_length=20, verbose_name='source · উৎস')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved · অনুমোদিত')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at · অনুমোদনের সময়')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed · বাতিল')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at · বাতিলের সময়')),
                ('reverse_reason', models.TextField(blank=True, verbose_name='reversal reason · বাতিলের কারণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by · অনুমোদনকারী')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recorded by · লিপিবদ্ধকারী')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by · বাতিলকারী')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='branches.session', verbose_name='session · শিক্ষাবর্ষ')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.expensecategory', verbose_name='category · খাত')),
            ],
            options={
                'verbose_name': 'expense · ব্যয়',
                'verbose_name_plural': 'expenses · ব্যয়সমূহ',
                'ordering': ['branch', '-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='code · কোড')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=80, verbose_name='নাম')),
                ('note', models.TextField(blank=True, verbose_name='note · নোট')),
                ('note_bn', models.TextField(blank=True, verbose_name='নোট')),
                ('is_system', models.BooleanField(default=False, verbose_name='seeded · পূর্বনির্ধারিত')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='order · ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_categories', to='fees.feecategory', verbose_name='fee category · ফি খাত')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'income category · আয়ের খাত',
                'verbose_name_plural': 'income categories · আয়ের খাতসমূহ',
                'ordering': ['branch', 'display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_no', models.CharField(max_length=30, verbose_name='voucher no · ভাউচার নম্বর')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount · পরিমাণ')),
                ('date', models.DateField(verbose_name='date · তারিখ')),
                ('method', models.CharField(choices=[('cash', 'Cash · নগদ টাকা'), ('bkash', 'bKash · বিকাশ'), ('nagad', 'Nagad · নগদ'), ('rocket', 'Rocket · রকেট'), ('bank', 'Bank · ব্যাংক'), ('cheque', 'Cheque · চেক'), ('card', 'Card · কার্ড'), ('online', 'Online · অনলাইন')], default='cash', max_length=20, verbose_name='method · মাধ্যম')),
                ('reference', models.CharField(blank=True, default='', help_text='Transaction id, cheque number, bill number.', max_length=120, verbose_name='reference · সূত্র')),
                ('description', models.TextField(blank=True, verbose_name='description · বিবরণ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/vouchers/%Y/%m/', verbose_name='attachment · সংযুক্তি')),
                ('source', models.CharField(choices=[('manual', 'Entered manually · হাতে লেখা'), ('fee_payment', 'Fee collection · ফি আদায়'), ('payroll', 'Payroll · বেতন')], default='manual', max_length=20, verbose_name='source · উৎস')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved · অনুমোদিত')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at · অনুমোদনের সময়')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed · বাতিল')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at · বাতিলের সময়')),
                ('reverse_reason', models.TextField(blank=True, verbose_name='reversal reason · বাতিলের কারণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by · অনুমোদনকারী')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='fees.payment', verbose_name='payment · আদায়')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recorded by · লিপিবদ্ধকারী')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by · বাতিলকারী')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='branches.session', verbose_name='session · শিক্ষাবর্ষ')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.incomecategory', verbose_name='category · খাত')),
            ],
            options={
                'verbose_name': 'income · আয়',
                'verbose_name_plural': 'income · আয়সমূহ',
                'ordering': ['branch', '-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='expensecategory_unique_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'date'], name='expense_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'category', 'date'], name='expense_branch_cat_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('branch', 'voucher_no'), name='expense_unique_voucher_no'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='incomecategory_unique_code_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_category__isnull', False)), fields=('branch', 'fee_category'), name='incomecategory_one_head_per_fee_category'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['branch', 'date'], name='income_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['branch', 'category', 'date'], name='income_branch_cat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['branch', 'source'], name='income_branch_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('branch', 'voucher_no'), name='income_unique_voucher_no'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='income_one_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='income_amount_positive'),
        ),
    ]
