# Generated by Django 5.1.4 on 2026-09-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Saturday · শনিবার'), (1, 'Sunday · রবিবার'), (2, 'Monday · সোমবার'), (3, 'Tuesday · মঙ্গলবার'), (4, 'Wednesday · বুধবার'), (5, 'Thursday · বৃহস্পতিবার'), (6, 'Friday · শুক্রবার')], verbose_name='day · দিন')),
                ('room', models.CharField(blank=True, max_length=40, verbose_name='room · কক্ষ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'routine · রুটিন',
                'verbose_name_plural': 'routines · রুটিন',
                'ordering': ['branch', 'day_of_week', 'period', 'academic_class'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll', models.PositiveIntegerField(verbose_name='roll · রোল')),
                ('admission_number', models.CharField(max_length=30, verbose_name='admission number · ভর্তি নম্বর')),
                ('status', models.CharField(choices=[('active', 'Active · অধ্যয়নরত'), ('promoted', 'Promoted · উত্তীর্ণ'), ('passed', 'Passed out · সমাপ্ত'), ('withdrawn', 'Withdrawn · প্রত্যাহার'), ('transferred', 'Transferred · স্থানান্তরিত')], default='active', max_length=20, verbose_name='status · অবস্থা')),
                ('enrolled_on', models.DateField(verbose_name='enrolled on · ভর্তির তারিখ')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='left on · প্রস্থানের তারিখ')),
                ('is_hostel', models.BooleanField(default=False, verbose_name='hostel · আবাসিক')),
                ('is_transport', models.BooleanField(default=False, verbose_name='transport · পরিবহন')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'enrolment · ভর্তি',
                'verbose_name_plural': 'enrolments · ভর্তিসমূহ',
                'ordering': ['branch', '-session', 'academic_class', 'section', 'roll'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=30, verbose_name='নাম')),
                ('order', models.PositiveIntegerField(verbose_name='order · ক্রম')),
                ('start_time', models.TimeField(verbose_name='starts · শুরু')),
                ('end_time', models.TimeField(verbose_name='ends · শেষ')),
                ('is_break', models.BooleanField(default=False, verbose_name='break · বিরতি')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'period · ঘণ্টা',
                'verbose_name_plural': 'periods · ঘণ্টাসমূহ',
                'ordering': ['branch', 'stream', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, verbose_name='name · নাম')),
                ('name_bn', models.CharField(blank=True, max_length=40, verbose_name='নাম')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity · আসন')),
                ('room', models.CharField(blank=True, max_length=40, verbose_name='room · কক্ষ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'section · শাখা',
                'verbose_name_plural': 'sections · শাখাসমূহ',
                'ordering': ['branch', 'academic_class', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=80, verbose_name='নাম')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code · কোড')),
                ('full_marks', models.PositiveIntegerField(default=100, verbose_name='full marks · পূর্ণমান')),
                ('pass_marks', models.PositiveIntegerField(default=33, verbose_name='pass marks · পাস নম্বর')),
                ('is_optional', models.BooleanField(default=False, verbose_name='optional · ঐচ্ছিক')),
                ('has_practical', models.BooleanField(default=False, verbose_name='has practical · ব্যবহারিক আছে')),
                ('practical_marks', models.PositiveIntegerField(default=0, verbose_name='practical marks · ব্যবহারিক নম্বর')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'subject · বিষয়',
                'verbose_name_plural': 'subjects · বিষয়সমূহ',
                'ordering': ['branch', 'academic_class', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
            ],
            options={
                'verbose_name': 'subject assignment · বিষয় বণ্টন',
                'verbose_name_plural': 'subject assignments · বিষয় বণ্টন',
                'ordering': ['branch', '-session', 'academic_class', 'subject'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('name_bn', models.CharField(blank=True, max_length=60, verbose_name='নাম')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='year · সাল')),
                ('level_order', models.PositiveIntegerField(default=0, verbose_name='level · স্তর')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity · আসন')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly fee · মাসিক বেতন')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
            ],
            options={
                'verbose_name': 'class · শ্রেণি',
                'verbose_name_plural': 'classes · শ্রেণিসমূহ',
                'ordering': ['branch', '-year', 'level_order', 'name'],
                'abstract': False,
            },
        ),
    ]
