# Generated by Django 5.1.4 on 2026-09-10 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('branches', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_in_charge', to='staff.teacher', verbose_name='class teacher · শ্রেণি শিক্ষক'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='branches.session', verbose_name='session · শিক্ষাবর্ষ'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='branches.stream', verbose_name='stream · শাখা'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.academicclass', verbose_name='class · শ্রেণি'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='branches.session', verbose_name='session · শিক্ষাবর্ষ'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='staff.teacher', verbose_name='teacher · শিক্ষক'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.academicclass', verbose_name='class · শ্রেণি'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='branches.session', verbose_name='session · শিক্ষাবর্ষ'),
        ),
    ]
