# Generated by Django 5.1.4 on 2026-09-10 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('branches', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='students.student', verbose_name='student · শিক্ষার্থী'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='period',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='period',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='period',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='branches.stream', verbose_name='stream · শাখা'),
        ),
        migrations.AddField(
            model_name='period',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='academics.period', verbose_name='period · ঘণ্টা'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicclass', verbose_name='class · শ্রেণি'),
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_in_charge', to='staff.teacher', verbose_name='in charge · দায়িত্বপ্রাপ্ত শিক্ষক'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.section', verbose_name='section · শাখা'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.section', verbose_name='section · শাখা'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.academicclass', verbose_name='class · শ্রেণি'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='branches.stream', verbose_name='stream · শাখা'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='academics.subject', verbose_name='subject · বিষয়'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.academicclass', verbose_name='class · শ্রেণি'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.section', verbose_name='section · শাখা'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_assignments', to='branches.session', verbose_name='session · শিক্ষাবর্ষ'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject', verbose_name='subject · বিষয়'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_assignments', to='staff.teacher', verbose_name='teacher · শিক্ষক'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academicclass',
            index=models.Index(fields=['branch', 'session', 'level_order'], name='class_branch_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('branch', 'session', 'stream', 'name'), name='class_unique_per_session_stream'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False)), fields=('branch', 'stream', 'order'), name='period_unique_order_per_stream'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', True)), fields=('branch', 'order'), name='period_unique_order_branch_wide'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='period_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('academic_class', 'name'), name='section_unique_per_class'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['branch', 'session', 'status'], name='enrolment_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['branch', 'academic_class', 'section'], name='enrolment_class_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('branch', 'session', 'academic_class', 'section', 'roll'), name='enrolment_unique_roll_per_section'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('branch', 'session', 'academic_class', 'roll'), name='enrolment_unique_roll_per_class'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('branch', 'admission_number'), name='enrolment_unique_admission_number'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('branch', 'session', 'student'), name='enrolment_one_per_student_per_session'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('academic_class', 'name'), name='subject_unique_name_per_class'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__lte', models.F('full_marks'))), name='subject_pass_within_full'),
        ),
        migrations.AddIndex(
            model_name='classroutine',
            index=models.Index(fields=['branch', 'teacher', 'day_of_week'], name='routine_teacher_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroutine',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('branch', 'session', 'academic_class', 'section', 'day_of_week', 'period'), name='routine_unique_slot_per_section'),
        ),
        migrations.AddConstraint(
            model_name='classroutine',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('branch', 'session', 'academic_class', 'day_of_week', 'period'), name='routine_unique_slot_per_class'),
        ),
        migrations.AddConstraint(
            model_name='classroutine',
            constraint=models.UniqueConstraint(fields=('branch', 'session', 'teacher', 'day_of_week', 'period'), name='routine_unique_teacher_slot'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['branch', 'session', 'teacher'], name='assignment_teacher_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('branch', 'session', 'teacher', 'subject', 'academic_class', 'section'), name='assignment_unique_with_section'),
        ),
        migrations.AddConstraint(
            model_name='subjectassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('branch', 'session', 'teacher', 'subject', 'academic_class'), name='assignment_unique_without_section'),
        ),
    ]
