# Generated by Django 5.1.4 on 2026-09-10 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('admission', 'Admission number · ভর্তি নম্বর'), ('roll', 'Roll · রোল'), ('teacher', 'Teacher id · শিক্ষক আইডি'), ('employee', 'Employee id · কর্মচারী আইডি'), ('student', 'Student id · শিক্ষার্থী আইডি'), ('application', 'Application number · আবেদন নম্বর')], max_length=20)),
                ('scope', models.CharField(blank=True, default='', max_length=60)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL means the counter is platform-wide, not per institution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'number sequence · ক্রমিক নম্বর',
                'verbose_name_plural': 'number sequences · ক্রমিক নম্বরসমূহ',
                'ordering': ['branch', 'kind', 'scope'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'kind', 'scope'), name='numberseq_unique_per_branch'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('kind', 'scope'), name='numberseq_unique_platform_wide')],
            },
        ),
    ]
