# Generated by Django 5.1.4 on 2026-09-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbersequence',
            name='kind',
            field=models.CharField(choices=[('admission', 'Admission number · ভর্তি নম্বর'), ('roll', 'Roll · রোল'), ('teacher', 'Teacher id · শিক্ষক আইডি'), ('employee', 'Employee id · কর্মচারী আইডি'), ('student', 'Student id · শিক্ষার্থী আইডি'), ('application', 'Application number · আবেদন নম্বর'), ('form', 'Printed form number · ফরম নম্বর'), ('receipt', 'Receipt number · রসিদ নম্বর'), ('invoice', 'Invoice number · চালান নম্বর'), ('income_voucher', 'Income voucher · আয় ভাউচার'), ('expense_voucher', 'Expense voucher · ব্যয় ভাউচার')], max_length=20),
        ),
    ]
