# Generated by Django 5.1.4 on 2026-09-10 02:06

import accounts.managers
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, help_text='Canonical 01XXXXXXXXX. +88 and dashed forms are accepted and normalised.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^01[3-9]\\d{8}$', 'Enter an 11-digit mobile number, e.g. 01712345678.')])),
                ('name', models.CharField(max_length=120)),
                ('name_bn', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_type', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('employee', 'Employee'), ('student', 'Student'), ('guardian', 'Guardian')], db_index=True, default='employee', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('language', models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English')], default='bn', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can sign in to the Django admin. Unrelated to institution staff.')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['name', 'phone'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(blank=True, max_length=160)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged in'), ('login_failed', 'Failed login'), ('collect', 'Collected payment'), ('waive', 'Waived fee'), ('publish', 'Published results'), ('take_attendance', 'Took attendance')], db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('summary_bn', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'activity log entry',
                'verbose_name_plural': 'activity log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=80)),
                ('permission_matrix', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
    ]
