# Generated by Django 5.1.4 on 2026-09-10 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('branches', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date · তারিখ')),
                ('status', models.CharField(choices=[('present', 'Present · উপস্থিত'), ('absent', 'Absent · অনুপস্থিত'), ('late', 'Late · বিলম্বে উপস্থিত'), ('leave', 'Leave · ছুটি'), ('holiday', 'Holiday · সরকারি ছুটি'), ('half_day', 'Half day · অর্ধদিবস')], max_length=10, verbose_name='status · অবস্থা')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='remarks · মন্তব্য')),
                ('taken_at', models.DateTimeField(verbose_name='taken at · গ্রহণের সময়')),
                ('source', models.CharField(choices=[('web', 'Web · ওয়েব'), ('mobile', 'Mobile · মোবাইল'), ('biometric', 'Biometric · বায়োমেট্রিক'), ('import', 'Imported · আমদানি')], default='web', max_length=10, verbose_name='source · উৎস')),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_attendance', to='academics.academicclass')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance', to='academics.enrolment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_attendance', to='academics.period')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_attendance', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_attendance', to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_attendance', to='academics.subject')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance_taken', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class attendance · ক্লাস হাজিরা',
                'verbose_name_plural': 'class attendance · ক্লাস হাজিরা',
                'ordering': ['branch', 'date', 'period', 'academic_class', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'date', 'academic_class'], name='classatt_branch_date_class'), models.Index(fields=['student', 'date'], name='classatt_student_date'), models.Index(fields=['period', 'date'], name='classatt_period_date')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date', 'academic_class', 'section', 'period', 'student'), name='classatt_unique_period_student'), models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('branch', 'date', 'academic_class', 'period', 'student'), name='classatt_unique_no_section')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date · তারিখ')),
                ('person_type', models.CharField(choices=[('student', 'Student · শিক্ষার্থী'), ('teacher', 'Teacher · শিক্ষক'), ('employee', 'Employee · কর্মচারী')], db_index=True, max_length=10, verbose_name='person type · ব্যক্তির ধরন')),
                ('status', models.CharField(choices=[('present', 'Present · উপস্থিত'), ('absent', 'Absent · অনুপস্থিত'), ('late', 'Late · বিলম্বে উপস্থিত'), ('leave', 'Leave · ছুটি'), ('holiday', 'Holiday · সরকারি ছুটি'), ('half_day', 'Half day · অর্ধদিবস')], max_length=10, verbose_name='status · অবস্থা')),
                ('in_time', models.TimeField(blank=True, null=True, verbose_name='in time · প্রবেশ')),
                ('out_time', models.TimeField(blank=True, null=True, verbose_name='out time · প্রস্থান')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='remarks · মন্তব্য')),
                ('taken_at', models.DateTimeField(verbose_name='taken at · গ্রহণের সময়')),
                ('source', models.CharField(choices=[('web', 'Web · ওয়েব'), ('mobile', 'Mobile · মোবাইল'), ('biometric', 'Biometric · বায়োমেট্রিক'), ('import', 'Imported · আমদানি')], default='web', max_length=10, verbose_name='source · উৎস')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='staff.employee')),
                ('enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance', to='academics.enrolment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='students.student')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_taken', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='staff.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily attendance · দৈনিক হাজিরা',
                'verbose_name_plural': 'daily attendance · দৈনিক হাজিরা',
                'ordering': ['branch', 'date', 'person_type', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'date', 'person_type'], name='dailyatt_branch_date_type'), models.Index(fields=['student', 'date'], name='dailyatt_student_date'), models.Index(fields=['enrolment', 'date'], name='dailyatt_enrolment_date'), models.Index(fields=['teacher', 'date'], name='dailyatt_teacher_date'), models.Index(fields=['employee', 'date'], name='dailyatt_employee_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', True), ('person_type', 'student'), ('student__isnull', False), ('teacher__isnull', True)), models.Q(('employee__isnull', True), ('person_type', 'teacher'), ('student__isnull', True), ('teacher__isnull', False)), models.Q(('employee__isnull', False), ('person_type', 'employee'), ('student__isnull', True), ('teacher__isnull', True)), _connector='OR'), name='dailyatt_exactly_one_person'), models.UniqueConstraint(fields=('branch', 'date', 'person_type', 'student', 'teacher', 'employee'), name='dailyatt_unique_person_day'), models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('branch', 'date', 'student'), name='dailyatt_unique_student_day'), models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('branch', 'date', 'teacher'), name='dailyatt_unique_teacher_day'), models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('branch', 'date', 'employee'), name='dailyatt_unique_employee_day')],
            },
        ),
    ]
