# Generated by Django 5.1.4 on 2026-09-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('branches', '0004_sms_event_switches'),
        ('forms', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='name · নাম')),
                ('name_bn', models.CharField(blank=True, max_length=80, verbose_name='নাম')),
                ('frequency', models.CharField(choices=[('daily', 'Daily · প্রতিদিন'), ('weekly', 'Weekly · সাপ্তাহিক'), ('monthly', 'Monthly · মাসিক'), ('term', 'Per term · সাময়িক')], default='daily', max_length=10, verbose_name='frequency · কত ঘনঘন')),
                ('section', models.CharField(default='conduct', max_length=60, verbose_name='question section · প্রশ্নের অংশ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='academics.academicclass', verbose_name='class · শ্রেণি')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='branches.stream', verbose_name='বিভাগ · stream')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report template · রিপোর্টের নমুনা',
                'verbose_name_plural': 'report templates · রিপোর্টের নমুনা',
                'ordering': ['branch', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=12, verbose_name='period · সময়')),
                ('status', models.CharField(choices=[('draft', 'Draft · খসড়া'), ('submitted', 'Submitted · জমা')], default='submitted', max_length=10, verbose_name='status · অবস্থা')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='remarks · মন্তব্য')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='filled at · সময়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduct_reports', to='academics.enrolment', verbose_name='enrolment · ভর্তি')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_reports', to='staff.teacher', verbose_name='filled by · যিনি দিয়েছেন')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduct_reports', to='students.student', verbose_name='student · শিক্ষার্থী')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='conduct.reporttemplate', verbose_name='template · নমুনা')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student report · শিক্ষার্থীর রিপোর্ট',
                'verbose_name_plural': 'student reports · শিক্ষার্থীর রিপোর্ট',
                'ordering': ['-period', 'enrolment_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(blank=True, null=True, verbose_name='answer · উত্তর')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduct_answers', to='forms.question', verbose_name='question · প্রশ্ন')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='conduct.studentreport', verbose_name='report · রিপোর্ট')),
            ],
            options={
                'verbose_name': 'report answer · উত্তর',
                'verbose_name_plural': 'report answers · উত্তর',
                'ordering': ['report', 'item__order', 'item_id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='reporttemplate_unique_name_per_branch'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['branch', 'template', 'period'], name='studentreport_sheet_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreport',
            index=models.Index(fields=['student', '-period'], name='studentreport_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentreport',
            constraint=models.UniqueConstraint(fields=('branch', 'template', 'enrolment', 'period'), name='studentreport_one_per_period'),
        ),
        migrations.AddConstraint(
            model_name='reportanswer',
            constraint=models.UniqueConstraint(fields=('report', 'item'), name='reportanswer_one_per_item'),
        ),
    ]
