# Generated by Django 5.1.4 on 2026-09-23 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('branches', '0004_sms_event_switches'),
        ('conduct', '0001_initial'),
        ('forms', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduct_assignments', to='academics.academicclass', verbose_name='class · শ্রেণি')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conduct_assignments', to='academics.section', verbose_name='section · শাখা')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduct_assignments', to='staff.teacher', verbose_name='teacher · শিক্ষক')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conduct.reporttemplate', verbose_name='template · নমুনা')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report assignment · রিপোর্টের দায়িত্ব',
                'verbose_name_plural': 'report assignments · রিপোর্টের দায়িত্ব',
                'ordering': ['template', 'academic_class', 'section', 'teacher'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('template', 'academic_class', 'section', 'teacher'), name='reportassignment_once_per_section'), models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('template', 'academic_class', 'teacher'), name='reportassignment_once_per_class')],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order · ক্রম')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_links', to='forms.question', verbose_name='question · প্রশ্ন')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='conduct.reporttemplate', verbose_name='template · নমুনা')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'template question · নমুনার প্রশ্ন',
                'verbose_name_plural': 'template questions · নমুনার প্রশ্ন',
                'ordering': ['template', 'order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('template', 'question'), name='templatequestion_once_per_template')],
            },
        ),
    ]
