# Generated by Django 5.1.4 on 2026-09-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_seed_grade_scales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeband',
            options={'ordering': ['scale_id', '-min_percent'], 'verbose_name': 'grade band · গ্রেড', 'verbose_name_plural': 'grade bands · গ্রেডসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['branch_id', 'stream_id', 'name'], 'verbose_name': 'grade scale · গ্রেডিং পদ্ধতি', 'verbose_name_plural': 'grade scales · গ্রেডিং পদ্ধতি'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['exam_id', 'enrolment_id'], 'verbose_name': 'result · ফলাফল', 'verbose_name_plural': 'results · ফলাফল'},
        ),
    ]
