# Generated by Django 5.1.4 on 2026-09-22 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_branch_sms_enabled'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('result_published', 'Result published · ফল প্রকাশ'), ('fee_due', 'Fee due · ফি বকেয়া'), ('fee_received', 'Fee received · ফি জমা'), ('absent', 'Absent · অনুপস্থিত'), ('notice', 'Notice · নোটিশ'), ('admission', 'Admission · ভর্তি')], max_length=24, verbose_name='event · ঘটনা')),
                ('channel', models.CharField(choices=[('sms', 'SMS · এসএমএস'), ('email', 'Email · ইমেইল')], default='sms', max_length=10, verbose_name='channel · মাধ্যম')),
                ('language', models.CharField(choices=[('bn', 'Bangla · বাংলা'), ('en', 'English · ইংরেজি')], default='bn', max_length=2, verbose_name='language · ভাষা')),
                ('body', models.TextField(verbose_name='body · বার্তা')),
                ('is_active', models.BooleanField(default=True, verbose_name='active · সক্রিয়')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification template · বার্তার নমুনা',
                'verbose_name_plural': 'notification templates · বার্তার নমুনা',
                'ordering': ['branch', 'event', 'language'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('branch', 'event', 'channel', 'language'), name='template_one_per_event_channel_language')],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('result_published', 'Result published · ফল প্রকাশ'), ('fee_due', 'Fee due · ফি বকেয়া'), ('fee_received', 'Fee received · ফি জমা'), ('absent', 'Absent · অনুপস্থিত'), ('notice', 'Notice · নোটিশ'), ('admission', 'Admission · ভর্তি')], max_length=24, verbose_name='event · ঘটনা')),
                ('reference', models.CharField(blank=True, max_length=40, verbose_name='reference · সূত্র')),
                ('recipient_label', models.CharField(blank=True, max_length=80, verbose_name='recipient · প্রাপক')),
                ('to_phone', models.CharField(blank=True, max_length=20, verbose_name='phone · ফোন')),
                ('body', models.TextField(verbose_name='body · বার্তা')),
                ('parts', models.PositiveSmallIntegerField(default=1, verbose_name='parts · খণ্ড')),
                ('status', models.CharField(choices=[('queued', 'Queued · সারিতে'), ('sent', 'Sent · পাঠানো হয়েছে'), ('failed', 'Failed · ব্যর্থ'), ('skipped', 'Skipped · বাদ')], default='queued', max_length=10, verbose_name='status · অবস্থা')),
                ('skip_reason', models.CharField(blank=True, choices=[('no_phone', 'No phone number · ফোন নম্বর নেই'), ('already_sent', 'Already sent · আগেই পাঠানো হয়েছে'), ('sms_off', 'SMS is switched off · এসএমএস বন্ধ')], max_length=20, verbose_name='skip reason · বাদ দেওয়ার কারণ')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='provider · সরবরাহকারী')),
                ('provider_code', models.CharField(blank=True, max_length=10, verbose_name='provider code · কোড')),
                ('provider_message', models.CharField(blank=True, max_length=200, verbose_name='provider message · বার্তা')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at · পাঠানোর সময়')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts · চেষ্টা')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='students.student', verbose_name='student · শিক্ষার্থী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS message · এসএমএস',
                'verbose_name_plural': 'SMS messages · এসএমএস',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', '-created_at'], name='sms_branch_recent'), models.Index(fields=['branch', 'event', 'reference'], name='sms_branch_event_ref')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'sent'])), fields=('branch', 'event', 'reference', 'to_phone'), name='sms_one_live_message_per_recipient')],
            },
        ),
    ]
